# Generated by Django 6.0.5 on 2026-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pasport_num',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
