# Generated by Django 6.0.5 on 2026-05-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_pasport_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pasport_code',
            field=models.CharField(default='001-001', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='pasport_num',
            field=models.CharField(max_length=20),
        ),
    ]
