# Generated by Django 6.0.5 on 2026-05-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_pasport_code_alter_person_pasport_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pasport_otd',
            field=models.CharField(default='bebra', max_length=255),
            preserve_default=False,
        ),
    ]
