# Generated by Django 6.0.5 on 2026-05-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_person_pasport_otd'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pasport_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
