# Generated by Django 6.0.5 on 2026-05-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_pasport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='inn_fiz',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='oms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='snils',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
