# Generated by Django 6.0.5 on 2026-05-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_inn_fiz_person_oms_person_snils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='pasport_code',
            new_name='passport_code',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pasport_date',
            new_name='passport_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pasport_num',
            new_name='passport_num',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pasport_otd',
            new_name='passport_otd',
        ),
    ]
